services:
  minidlna:
    image: cytomich/rpi-docker-minidlna
    volumes:
      - /mnt/ext/av/:/media
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=Lime
    network_mode: "host"
    restart: always
